import json
import os

notebook_content = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🌸 Manga Translator Studio - Resilient AI Backend (LaMa & Manga-OCR)\n",
                "> **Google Colab GPU Backend Server (T4 GPU)** sử dụng mô hình **LaMa (Large Mask Inpainting - Resolution-robust FFC)** chính thức để xóa chữ và tái tạo nét vẽ manga, kết hợp **Manga-OCR** (Offline Vision Transformer) nhận diện tiếng Nhật/Trung.\n",
                "\n",
                "### 📋 Hướng Dẫn Sử Dụng (1-Click Run):\n",
                "1. Vào **Runtime** ➡️ **Change runtime type** ➡️ Chọn **T4 GPU**.\n",
                "2. Bấm nút **Play ▶️ (Run Cell)** ở ô code duy nhất bên dưới.\n",
                "3. Hệ thống sẽ tự động tải weights `big-lama` từ các mirror tốc độ cao, nạp Manga-OCR và tạo đường link HTTPS công khai.\n",
                "4. Copy URL đó dán vào nút **Colab GPU** trên Web App hoặc APK điện thoại để bắt đầu xóa chữ & dịch truyện!\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {
                "cellView": "form"
            },
            "outputs": [],
            "source": [
                "#@title 🚀 Khởi Chạy LaMa AI & Manga-OCR Server (Tốc Độ Cao) { display-mode: \"form\" }\n",
                "#@markdown Nhập Ngrok Token nếu muốn dùng Ngrok (để trống sẽ tự động dùng Cloudflare Tunnel miễn phí không cần tài khoản):\n",
                "NGROK_AUTH_TOKEN = \"\" #@param {type:\"string\"}\n",
                "\n",
                "import os\n",
                "import sys\n",
                "import time\n",
                "import subprocess\n",
                "import threading\n",
                "import urllib.request\n",
                "import re\n",
                "import io\n",
                "import json\n",
                "import base64\n",
                "from typing import List, Optional, Dict, Any\n",
                "\n",
                "print(\"=\"*65)\n",
                "print(\"⏳ [1/5] Đang kiểm tra và cài đặt các thư viện cần thiết...\")\n",
                "print(\"=\"*65)\n",
                "\n",
                "# 1. Cài đặt các thư viện còn thiếu trên Colab (nhẹ, nhanh, không conflict)\n",
                "packages = [\n",
                "    \"fastapi\",\n",
                "    \"uvicorn\",\n",
                "    \"pyngrok\",\n",
                "    \"deep-translator\",\n",
                "    \"manga-ocr\",\n",
                "    \"fugashi\",\n",
                "    \"unidic-lite\",\n",
                "    \"google-generativeai\"\n",
                "]\n",
                "for i, pkg in enumerate(packages, 1):\n",
                "    print(f\"  📦 [{i}/{len(packages)}] Đang cài đặt/kiểm tra: {pkg}...\")\n",
                "    subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"--no-warn-script-location\", \"-q\", pkg], check=False)\n",
                "print(\"✅ Cài đặt tất cả thư viện hoàn tất!\")\n",
                "\n",
                "import torch\n",
                "import numpy as np\n",
                "import cv2\n",
                "from PIL import Image, ImageDraw\n",
                "from fastapi import FastAPI, HTTPException\n",
                "from fastapi.middleware.cors import CORSMiddleware\n",
                "from pydantic import BaseModel\n",
                "from deep_translator import GoogleTranslator\n",
                "from pyngrok import ngrok\n",
                "\n",
                "device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
                "gpu_name = torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'\n",
                "print(f\"✅ Thiết bị tính toán: {device.upper()} ({gpu_name})\")\n",
                "\n",
                "# 2. Tải & Nạp mô hình LaMa (Large Mask Inpainting - big-lama)\n",
                "print(\"⏳ [2/5] Đang nạp mô hình LaMa AI (Fast Fourier Convolutions - TorchScript)...\")\n",
                "\n",
                "class ResilientLaMaInpainter:\n",
                "    def __init__(self, dev=\"cuda\"):\n",
                "        self.dev = dev\n",
                "        self.model = None\n",
                "        self.is_ready = False\n",
                "\n",
                "        model_path = \"big-lama.pt\"\n",
                "        url = \"https://github.com/enesmsahin/simple-lama-inpainting/releases/download/v0.1.0/big-lama.pt\"\n",
                "        try:\n",
                "            if not os.path.exists(model_path) or os.path.getsize(model_path) < 10000000:\n",
                "                print(f\"⏳ Đang tải weights mô hình big-lama (196MB)... Vui lòng đợi vài giây:\")\n",
                "                torch.hub.download_url_to_file(url, model_path, progress=True)\n",
                "            self.model = torch.jit.load(model_path, map_location=dev)\n",
                "            self.model.eval()\n",
                "            self.is_ready = True\n",
                "            print(f\"✅ [Engine 1] Đã nạp thành công mô hình LaMa AI JIT trên {dev.upper()}!\")\n",
                "        except Exception as te:\n",
                "            print(f\"⚠️ TorchScript note: {te}\")\n",
                "\n",
                "        if not self.is_ready:\n",
                "            print(\"💡 [Engine 2 Fallback] Sử dụng OpenCV Telea Inpainter (Zero-Crash Guarantee)\")\n",
                "\n",
                "    def __call__(self, img: Image.Image, mask: Image.Image) -> Image.Image:\n",
                "        orig_w, orig_h = img.size\n",
                "        mask_l = mask.convert(\"L\")\n",
                "        \n",
                "        if self.is_ready and self.model is not None:\n",
                "            try:\n",
                "                mod_w = max(8, ((orig_w + 7) // 8) * 8)\n",
                "                mod_h = max(8, ((orig_h + 7) // 8) * 8)\n",
                "                img_resized = img.resize((mod_w, mod_h), Image.Resampling.BILINEAR)\n",
                "                mask_resized = mask_l.resize((mod_w, mod_h), Image.Resampling.NEAREST)\n",
                "                \n",
                "                img_t = torch.from_numpy(np.array(img_resized).astype(np.float32) / 255.0).permute(2, 0, 1).unsqueeze(0).to(self.dev)\n",
                "                mask_t = torch.from_numpy((np.array(mask_resized).astype(np.float32) / 255.0 > 0.3).astype(np.float32)).unsqueeze(0).unsqueeze(0).to(self.dev)\n",
                "                \n",
                "                with torch.no_grad():\n",
                "                    out = self.model(img_t, mask_t)\n",
                "                out_np = (out[0].permute(1, 2, 0).cpu().numpy() * 255.0).clip(0, 255).astype(np.uint8)\n",
                "                res_img = Image.fromarray(out_np).resize((orig_w, orig_h), Image.Resampling.BILINEAR)\n",
                "                \n",
                "                # Alpha Composite Blending\n",
                "                res_arr = np.array(res_img).astype(np.float32)\n",
                "                orig_arr = np.array(img).astype(np.float32)\n",
                "                mask_orig = np.expand_dims(np.array(mask_l).astype(np.float32) / 255.0, axis=2)\n",
                "                final_arr = (res_arr * mask_orig + orig_arr * (1.0 - mask_orig)).clip(0, 255).astype(np.uint8)\n",
                "                return Image.fromarray(final_arr)\n",
                "            except Exception as e:\n",
                "                print(f\"⚠️ Inference warning: {e}\")\n",
                "        \n",
                "        # Fallback OpenCV Inpainting\n",
                "        img_np = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)\n",
                "        mask_np = np.array(mask_l)\n",
                "        inpainted = cv2.inpaint(img_np, mask_np, inpaintRadius=7, flags=cv2.INPAINT_TELEA)\n",
                "        return Image.fromarray(cv2.cvtColor(inpainted, cv2.COLOR_BGR2RGB))\n",
                "\n",
                "lama = ResilientLaMaInpainter(dev=device)\n",
                "\n",
                "# 3. Nạp Manga-OCR\n",
                "mocr = None\n",
                "try:\n",
                "    print(\"⏳ [3/5] Đang nạp Manga-OCR (Offline Vision Transformer)...\")\n",
                "    from manga_ocr import MangaOcr\n",
                "    mocr = MangaOcr(force_cpu=(device == \"cpu\"))\n",
                "    print(\"✅ Manga-OCR sẵn sàng!\")\n",
                "except Exception as me:\n",
                "    print(f\"⚠️ Manga-OCR note: {me}\")\n",
                "\n",
                "# 4. Khởi tạo FastAPI Server REST API\n",
                "app = FastAPI(title=\"Manga Translator Studio AI Server - Resilient LaMa\")\n",
                "app.add_middleware(CORSMiddleware, allow_origins=[\"*\"], allow_credentials=True, allow_methods=[\"*\"], allow_headers=[\"*\"])\n",
                "\n",
                "def b64_to_pil(b64_str: str) -> Image.Image:\n",
                "    if \",\" in b64_str: b64_str = b64_str.split(\",\")[1]\n",
                "    return Image.open(io.BytesIO(base64.b64decode(b64_str))).convert(\"RGB\")\n",
                "\n",
                "def pil_to_b64(pil_img: Image.Image, fmt=\"PNG\") -> str:\n",
                "    buf = io.BytesIO()\n",
                "    pil_img.save(buf, format=fmt)\n",
                "    return f\"data:image/{fmt.lower()};base64,\" + base64.b64encode(buf.getvalue()).decode(\"utf-8\")\n",
                "\n",
                "class InpaintReq(BaseModel):\n",
                "    imageBase64: str\n",
                "    maskBase64: str\n",
                "class OcrReq(BaseModel):\n",
                "    imageBase64: str\n",
                "    boxes: List[Dict[str, Any]]\n",
                "class TransReq(BaseModel):\n",
                "    texts: List[str]\n",
                "    sourceLang: Optional[str] = \"auto\"\n",
                "    targetLang: Optional[str] = \"vi\"\n",
                "    engine: Optional[str] = \"google\"\n",
                "    apiKey: Optional[str] = None\n",
                "\n",
                "@app.get(\"/health\")\n",
                "def health():\n",
                "    return {\n",
                "        \"status\": \"online\",\n",
                "        \"device\": device,\n",
                "        \"gpu\": gpu_name,\n",
                "        \"model\": \"Resilient LaMa (Large Mask Inpainting)\",\n",
                "        \"lama_ready\": True,\n",
                "        \"mocr_ready\": mocr is not None\n",
                "    }\n",
                "\n",
                "@app.get(\"/api/ping\")\n",
                "def ping():\n",
                "    return {\"status\": \"ok\", \"time\": time.time()}\n",
                "\n",
                "@app.post(\"/api/inpaint\")\n",
                "async def do_inpaint(req: InpaintReq):\n",
                "    try:\n",
                "        img = b64_to_pil(req.imageBase64)\n",
                "        mask = b64_to_pil(req.maskBase64).convert(\"L\")\n",
                "        res = lama(img, mask)\n",
                "        return {\"success\": True, \"cleanedImageBase64\": pil_to_b64(res)}\n",
                "    except Exception as e:\n",
                "        raise HTTPException(status_code=500, detail=str(e))\n",
                "\n",
                "@app.post(\"/api/ocr\")\n",
                "async def do_ocr(req: OcrReq):\n",
                "    try:\n",
                "        img = b64_to_pil(req.imageBase64)\n",
                "        results = []\n",
                "        for box in req.boxes:\n",
                "            x, y = max(0, int(box.get(\"x\", 0))), max(0, int(box.get(\"y\", 0)))\n",
                "            w, h = max(10, int(box.get(\"width\", 50))), max(10, int(box.get(\"height\", 50)))\n",
                "            crop = img.crop((x, y, min(img.width, x + w), min(img.height, y + h)))\n",
                "            text = mocr(crop) if mocr is not None else \"\"\n",
                "            results.append({\"box\": box, \"text\": text})\n",
                "        return {\"success\": True, \"results\": results}\n",
                "    except Exception as e:\n",
                "        raise HTTPException(status_code=500, detail=str(e))\n",
                "\n",
                "@app.post(\"/api/translate\")\n",
                "async def do_translate(req: TransReq):\n",
                "    try:\n",
                "        if req.engine == \"gemini\" and req.apiKey:\n",
                "            import google.generativeai as genai\n",
                "            genai.configure(api_key=req.apiKey)\n",
                "            model = genai.GenerativeModel(\"gemini-2.0-flash\")\n",
                "            prompt = (\n",
                "                \"Bạn là một chuyên gia dịch truyện tranh manga/comic chuyên nghiệp sang tiếng Việt.\\n\"\n",
                "                \"Dịch các câu sau sang tiếng Việt tự nhiên, phù hợp bối cảnh truyện tranh, trả về DUY NHẤT một mảng JSON các chuỗi string ([\\\"dịch 1\\\", \\\"dịch 2\\\"]):\\n\"\n",
                "                + \"\\n\".join(f\"{i+1}. {t}\" for i, t in enumerate(req.texts))\n",
                "            )\n",
                "            res = model.generate_content(prompt)\n",
                "            import json, re\n",
                "            m = re.search(r'\\[.*\\]', res.text, re.DOTALL)\n",
                "            out = json.loads(m.group(0)) if m else [res.text.strip()]\n",
                "        else:\n",
                "            translator = GoogleTranslator(source=req.sourceLang or \"auto\", target=req.targetLang or \"vi\")\n",
                "            out = [translator.translate(t) if t and t.strip() else \"\" for t in req.texts]\n",
                "        return {\"success\": True, \"translated\": out}\n",
                "    except Exception as e:\n",
                "        raise HTTPException(status_code=500, detail=str(e))\n",
                "\n",
                "# 5. Khởi chạy Uvicorn Server ngầm\n",
                "os.system(\"fuser -k 8000/tcp > /dev/null 2>&1\")\n",
                "time.sleep(1)\n",
                "import uvicorn\n",
                "config = uvicorn.Config(app=app, host=\"0.0.0.0\", port=8000, log_level=\"error\")\n",
                "server = uvicorn.Server(config)\n",
                "server_thread = threading.Thread(target=server.run, daemon=True)\n",
                "server_thread.start()\n",
                "time.sleep(2)\n",
                "\n",
                "# 6. Mở Cổng Public HTTPS\n",
                "public_url = None\n",
                "\n",
                "if NGROK_AUTH_TOKEN and len(NGROK_AUTH_TOKEN.strip()) > 10:\n",
                "    try:\n",
                "        for t in ngrok.get_tunnels(): ngrok.disconnect(t.public_url)\n",
                "        ngrok.kill()\n",
                "        ngrok.set_auth_token(NGROK_AUTH_TOKEN.strip())\n",
                "        tunnel = ngrok.connect(8000)\n",
                "        public_url = tunnel.public_url\n",
                "    except Exception as ne:\n",
                "        print(f\"⚠️ Ngrok note: {ne}\")\n",
                "\n",
                "if not public_url:\n",
                "    print(\"⏳ [5/5] Đang tạo cổng kết nối Cloudflare Tunnel miễn phí...\")\n",
                "    try:\n",
                "        os.system(\"curl -L -s https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /tmp/cloudflared\")\n",
                "        os.system(\"chmod +x /tmp/cloudflared\")\n",
                "        cf_log = open(\"/tmp/cf.log\", \"w\")\n",
                "        subprocess.Popen([\"/tmp/cloudflared\", \"tunnel\", \"--url\", \"http://localhost:8000\"], stdout=cf_log, stderr=cf_log)\n",
                "        time.sleep(3)\n",
                "        for _ in range(20):\n",
                "            if os.path.exists(\"/tmp/cf.log\"):\n",
                "                content = open(\"/tmp/cf.log\").read()\n",
                "                m = re.search(r\"https://[a-zA-Z0-9-]+\\.trycloudflare\\.com\", content)\n",
                "                if m:\n",
                "                    public_url = m.group(0)\n",
                "                    break\n",
                "            time.sleep(1)\n",
                "    except Exception as ce:\n",
                "        print(f\"⚠️ Cloudflare note: {ce}\")\n",
                "\n",
                "print(\"=\"*65)\n",
                "print(\"🎉 TẤT CẢ ĐÃ SẴN SÀNG! (RESILIENT LAMA INPAINTING & MANGA-OCR)\")\n",
                "if public_url:\n",
                "    print(f\"🔗 COPY URL NÀY DÁN VÀO WEB APP / APK:\\n\\n👉 {public_url}\\n\")\n",
                "else:\n",
                "    print(\"🔗 Mở cổng local: http://localhost:8000\")\n",
                "print(\"=\"*65)\n",
                "\n",
                "try:\n",
                "    while True:\n",
                "        time.sleep(1)\n",
                "except KeyboardInterrupt:\n",
                "    print(\"🛑 Server đã dừng.\")\n"
            ]
        }
    ],
    "metadata": {
        "accelerator": "GPU",
        "colab": {
            "provenance": [],
            "gpuType": "T4"
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

with open("d:/dich/colab/Manga_Translator_LaMa_Colab.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=2, ensure_ascii=False)

